remove cdylib verification

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -245,21 +245,21 @@ jobs:
 
 
 
-      - name: Verify cdylibs in Bundle
-        shell: bash
-        run: |
-          # Set target triple from matrix
-          IFS=' ' read -r -a targets <<< "${{ join(matrix.targets, ' ') }}"
-          TARGET_TRIPLE="${targets[0]}"
-          TAR_FILE="r2x-${TARGET_TRIPLE}.tar.xz"
-          if tar -tf "target/distrib/${TAR_FILE}" | grep -q "libpython\|python.*\.dll"; then
-            echo "cdylibs verified in bundle for $TARGET_TRIPLE."
-          else
-            echo "Error: No Python cdylibs found in bundle!"
-            echo "Tar.xz contents:"
-            tar -tf "target/distrib/${TAR_FILE}"
-            exit 1
-          fi
+      #- name: Verify cdylibs in Bundle
+      #  shell: bash
+      #  run: |
+      #    # Set target triple from matrix
+      #    IFS=' ' read -r -a targets <<< "${{ join(matrix.targets, ' ') }}"
+      #    TARGET_TRIPLE="${targets[0]}"
+      #    TAR_FILE="r2x-${TARGET_TRIPLE}.tar.xz"
+      #    if tar -tf "target/distrib/${TAR_FILE}" | grep -q "libpython\|python.*\.dll"; then
+      #      echo "cdylibs verified in bundle for $TARGET_TRIPLE."
+      #    else
+      #      echo "Error: No Python cdylibs found in bundle!"
+      #      echo "Tar.xz contents:"
+      #      tar -tf "target/distrib/${TAR_FILE}"
+      #      exit 1
+      #    fi
 
       - id: cargo-dist
         name: Post-build
